# slurm 数据库配置
mysql:
  host: 10.99.81.153
  port: 3306
  user: root
  dbname: slurm_acct_db
  password: Msxf@2023
  clustername: cluster
  databaseencode: utf8mb4

# 服务端口设置
service:
  port: 8999

# slurm 默认Qos设置
slurm:
  defaultqos: normal

# module profile文件路径
modulepath:
  path: /lustre/software/module/5.2.0/init/profile.sh
  
